<br /><br /><center>View script for controller <b>member</b> and script/action name <b>index</b></center>

Member Entries: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <div>id: <?php echo $this->escape($entry->id) ?></div>
    <div>name: <?php echo $this->escape($entry->name) ?></div>
    <div>email: <?php echo $this->escape($entry->email) ?></div>
    <div>tel: <?php echo $this->escape($entry->tel) ?></div>
    <div>created: <?php echo $this->escape($entry->created) ?></div>
    <div>updated: <?php echo $this->escape($entry->updated) ?></div>
    <?php endforeach ?>
</dl>

<?php
#$this->form->setAction($this->url());
echo $this->form;
?>